# Generated by Django 5.1.4 on 2025-01-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_alter_receipe_receipie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipie_image',
            new_name='receipe_image',
        ),
    ]
